# Generated by Django 4.2.20 on 2025-04-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_required_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ship_to_location', models.TextField(blank=True, null=True)),
                ('required_certifications', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('main_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('main_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hq_address', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('price_per', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('minimum_order_quantity', models.BigIntegerField(blank=True, null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='compareapp.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='compareapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('related_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='compareapp.quote')),
            ],
        ),
    ]
