# Generated by Django 4.2.20 on 2025-04-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='price_per_pound',
            new_name='price_per',
        ),
    ]
